# Sample Docker Compose file for androidtvbackground
# - Set env vars below to True/False for which scripts you want to have run
# - Set user uid/gid to your hosts id's for volume mapping permissions. Default is 99:100
# - Change volume mappings to your local paths
# - Set a cron expression if you want to have backgrounds created on a schedule. ie: "0 0 * * *"
# - Update the scripts within the config volume mapping with your own API/URL settings
# - See full docker instructions at: https://github.com/ninthwalker/androidtvbackground
# - Androidtvbackground docker repo: https://github.com/adelatour11/androidtvbackground/tree/docker

services:
  androidtvbackground:
    image: ghcr.io/adelatour11/androidtvbackground:latest
    container_name: androidtvbackground
    network_mode: bridge
    user: 99:100
    volumes:
      - /your/local/path/for/config:/config
      - /your/local/path/for/backgrounds:/backgrounds
      # Optional: Uncomment and edit the line below to enable copying generated backgrounds
      # to a custom folder after creation. This works only if POST_SCRIPT_SH=True is set.
    environment:
      PLEX: False
      PLEXCOLOR: True
      PLEXFRIEND: False
      PLEXFRIENDCOLOR: True
      JELLYFIN: False
      TMDB: False
      TMDBCOLOR: True
      RADARRSONARR: False
      RADARRSONARRCOLOR: True
      TRAKT: False
      CRON: "0 0 * * *"
      # Note: If both POST_SCRIPT_PY and POST_SCRIPT_SH are set to True,
      # the Python script will run before the shell script.
      # Duplicate or conflicting code in both may cause errors or unexpected behavior.
      POST_SCRIPT_PY: False
      POST_SCRIPT_SH: true
      BASEURL: ${BASEURL}
      TOKEN: ${TOKEN}
